services:
- docker

script: "docker build -t navikt/nav-aapen-kildekode:$TRAVIS_COMMIT ."

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master

env:
  global:
  - secure: mdJw2st9C9AoVUy4wAx+gfXMb9PJwM8ROADINB1c8LS51V3w9bLWaklLZsR0meLvBYmXbKIXwlPpFpKen2ctENH/i6XpzwVIRrauZD2r1M77VVGRcsinvO1/2HFv5yLeDWgf3byAodbiz6EWY/pT0AwxH6rQHtRg81Ov7NW2woemwELzt4hDX7Oume9/d4awpRWVqxFkRQd21m0HY1PgiYuIK6DpMk/CczWSaXtNQ0eQM98sDb1h4Smnc70JfFSeaFVxmw7dKXkYHBu32xT5gWxr8Z+od1QM2esAN7WkeGMySNe5sWs8YM0FxK9ADOvOVFuGgxbDmbSIXc0wyFkkbremSRuiNC3zDGXK7UQyXJLAo0VaxCT2ClHtTx0MlbE7qJy1UPeg0gUWED/jgaBWUOnm3zwssa/94a1sBdr4kRF1WKcHnKSV0hVxc3fO6dSt2nhbgk/1EUPQAM5dXXxbRnlmPl8ihjKkMhKHPcWdumeSMMlLQnvTEqR0YCECjc+YYJ9LzzdVv1JeAGJyjrrfW72V0LhOzaf4Tssbazvyg/r1jeK9QRaJJcWX2CPMfMv4Jlol3SfIaG9DN/RF/TxzoKushGQ0SsCgGwNQqScVSYSus2mFZ9BHQ16QNmD6GwOZL4qZ5hCkVcSIHKH39lUAB0fBiIJsrPtzH4iWi4kv/pg=
  - secure: Nsj/FpWOI2v4H1kdponE423Awli6KjWkFKGjyiURamfL6qsKVMRKCIL57tQZdiH/Iy4KdkjZdckex0WLA5dy18hTELkNEA7RkJyNDbBRRQLeDoxSPwvWFp0eE6JEWOb409977gT2PF4110EU0uwLJ8zu9mnHvU7xkwdkUM+jwtZVSbfirDsnSAWESS86IZtwNgAT7vsvxib3mHGI/6x812b5+5+J/Wq0jdhpt4ZdFFLqKELxjmH5A+vYJirJ++25qpzn856DdBGijh1FGpfK45wmZVhOM6AW1ztjG0hvjFSvyP2abqyMJkdkgBkaVgSkr7/+rhozpKjZelTG/DsrHdjQrnBRL8HORZLT23JRh+PVGeLNZSjyVB+IYHJ4vRYfYyJzH+KTyzHMp03g1wUaTw2QjhzPNzD7FNRPo866kl341L4ewM+74qN9HoCPIqVDA/qH4rkdrpcg9fUIukeoiRlmQRXFlPlCxe4OqXvYmI/1Yjb9h9f4zXw96/OpD6SEOyVmXM4tm1k4bM51KgX/hbz66ffet/j2PA6+FrCyHxQlgfr8iivpAUcE1gZs4u2F2oUg6yIuqGWQoQUlkH2eSfi0ss5Hf+ZHLNXzc9l2g9mySydw9yWKsDeo4YEDLi+W2KPQQNJcu3nzMRS6g/I94l0rPUlZ84FbJ1dk6+i15uQ=
