services:
- docker

script: docker build -t navikt/nav-aapen-kildekode .

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master

env:
  global:
  - secure: gDPkDyfB0XZVKnmiOII4mX6xWTpzKrKtQaA/n8ffS2mh4EM1r59rLClQr4smHLckiSn1+Sb7ky1crpfF99MuOP9BfBCY1EoameVDtMsudP5mhCZmemlwX4eL9yunWw4xbCRJ+j6O7nHzM4L+c22a1NqwvsolocBO9GxCKjfaGhsb4DBSHKWSKRJo5ZAIAE02LnOuuWX1H+ciUuCjDV8okfdx1SMeWEIH+TfkyOWb36WpOQ/4b/yQVC3rZs1vJUsVoa0/Rh0J41A6Z2K2kkbFO+RSoVy2Ux8GB5GTs0JqfOd//+pvbDhiaPY3Fmtdc0pl+xw57bm1XanskP6aVz8mZVCSaSTKT1+WEyeeDJLufSss/zquxZkSIPp45RsWJyrT0B3KxQZqhg3GtZq/g8HDEO7VmxxwZ1Mm7Yq76B4lu1M5LDuRSZDWHGyi/xjW9tAp0ztIoDS9aJc1IsvV0Ry+1S86gl+40AISUEMmCPm9HSS3FWU3Y52/XxUfw8Q/dAYFi4lEWu0Aw72FRy1WNadQD6gV7HAZlshIrGcIvdOVbSWxMqT9UOTgHr+mRMhsMefyghZazOB46we1miKpqqVi9Rkd9jWMPQ8332tyV1N7n7iH5c7Bxyql8krHjJ0zFE2pSHImuzQyhx0gpASTtgmKRtzhsBUtA/ESotr8WR5zTFI=
  - secure: aWBKZzmYoy52/FvGZcYmeOfCqmWUhEz2et8Zv9USQ15SRWHAkIHP27YwPzU8++STLUkCTL4xhG+JcFgURdL3fJf5/jG8bW/U7HDeNquI/LZFzqd2cKIe62qpoy4JlfKrIWRCgtilyPW3Re2mXnKz5uwqClrjmXXLoB6U0wFmp/dsJYlXrbvVJLADwngSPxk70agH38BHyZ0PGNTjRTXHRaGXmqh/nJrnOXF6PPIJ0UcU/VVW1vSVi1GDGRh+6jVgPy0gflV4AERcYa6adMJWgnARzK4XY3GjfRuWI5aS8VwauNk2BFyMcEJu+v0gGBQxToej35/fTnDnJKANqsEDcGRAOdcxtKC3LrqDSoBkgtJfMRx6noRf2c3cCaInNemZxTggZTbLrApzHyukPNBOcCx5aMn7hD0HFkZs5aSp5PLFYgMIaRZmztag1dzneSxPIXm4y4WH8yjHWSQ7AzMyACj58FPk7Of4RSKuxvwi+nAG1PpF8iFcL8U6+jui6YxGp1e57DumtyGvfcRDon3Tr3kaqpma6nG2tEii+R49jUPHLNb+SrC+3nAPdHLOZjQR2AD6E8MtADmC76BL0Xd6euhznQmv8H0rhjbwoPQvmCqAaDapQuaOFW+cAtemrzYHITljnqPcjKxysmA6LA6Vll35CGkzyFoQpNCZusQi/EQ=
